# #################################
#
#  Use this file to set additional configurations for Helm to use for the Kubernetes cluster
#  See for the example  https://github.com/10gen/helm-charts/blob/master/charts/web-app/values.yaml
#
# #################################

ingress:
  enabled: true
  path: /api
  hosts:
    - sc-portal.sc-north.staging.corp.mongodb.com

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 50m
    memory: 400Mi

# Entries here refer back to secrets created in helm and visibile in the Kanopy portal
# the value here (sc-portal in this case) is the "secrets list" that we want to use. And
# it contains a secret named DB_URL that will be matched up to this DB_URL entry:
#
#    DB_URL:                            sc-portal
#    name of env to expose              Secrets list to use for the values in the first part
#    of of secret inside secret
#     list to get the value from
#
envSecrets:
  DB_URL: sc-portal